version: '3.8'

services:
  telegram-iptv-bot:
    build: .
    container_name: telegram-iptv-bot
    env_file: .env
    volumes:
      - telegram_iptv_data:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  telegram_iptv_data:
    driver: local
